// Garmin TRI CT113 倒數 100 天課表
// 比賽日期：2026/4/25 (星期六) - Challenge Taiwan
// 訓練開始：2026/1/12 (星期一)
// 課表來源：Garmin TRI 訓練營

export const garminTriData = [
    // Week 1 - 基礎強化期 (1/12-1/18)
    { day: "Week 1 - Day 1 (週一)", status: "No", intensity: "中等", date: "January 12, 2026", swim: "3", bike: "60", content: "自行車：60min 暖身騎 50%-60% FTP | 游泳：3000m (400m暖身 + 3x500m蛙/自 + 200m整理)", hours: 2.5, type: "有氧訓練", run: "", week: "Week 1", phase: "基礎強化期" },
    { day: "Week 1 - Day 2 (週二)", status: "No", intensity: "中等", date: "January 13, 2026", swim: "2.5", bike: "", content: "游泳：2500m (400m暖身 + 4x400m姿勢調整 + 350m整理) | 跑步：30min 慢跑", hours: 2, type: "技術課", run: "5", week: "Week 1", phase: "基礎強化期" },
    { day: "Week 1 - Day 3 (週三)", status: "No", intensity: "中等", date: "January 14, 2026", swim: "1.4", bike: "30", content: "自行車：30min 80% FTP 踏頻90+ | 游泳：12x100m踏頻 + 200m整理 | 核心訓練60min", hours: 2, type: "配速訓練", run: "", week: "Week 1", phase: "基礎強化期" },
    { day: "Week 1 - Day 4 (週四)", status: "No", intensity: "輕鬆", date: "January 15, 2026", swim: "1.5", bike: "", content: "游泳：6x50m自由式 + 2x200m輕鬆游 + 2x300m臂划 | 瑜珈訓練", hours: 1.5, type: "技術課", run: "", week: "Week 1", phase: "基礎強化期" },
    { day: "Week 1 - Day 5 (週五)", status: "No", intensity: "中等", date: "January 16, 2026", swim: "", bike: "", content: "跑步(早)：10min暖身 + 2x20min輕鬆跑 | 跑步(晚)：2x20min間歇", hours: 2, type: "間歇訓練", run: "12", week: "Week 1", phase: "基礎強化期" },
    { day: "Week 1 - Day 6 (週六)", status: "No", intensity: "休息", date: "January 17, 2026", swim: "", bike: "", content: "輕鬆恢復騎乘（建議休息）| 下午休息", hours: 0.5, type: "輕鬆恢復", run: "", week: "Week 1", phase: "基礎強化期" },
    { day: "Week 1 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "January 18, 2026", swim: "2", bike: "", content: "跑步：30min慢跑 | 游泳：45min慢游約2km", hours: 1.5, type: "輕鬆恢復", run: "5", week: "Week 1", phase: "基礎強化期" },

    // Week 2 - 基礎強化期 (1/19-1/25)
    { day: "Week 2 - Day 1 (週一)", status: "No", intensity: "中等", date: "January 19, 2026", swim: "2.5", bike: "90", content: "自行車：90min輕鬆恢復 | 游泳：250m暖身 + 2x500m輕鬆游 + 3x300m有氧游", hours: 3, type: "有氧訓練", run: "", week: "Week 2", phase: "基礎強化期" },
    { day: "Week 2 - Day 2 (週二)", status: "No", intensity: "中等", date: "January 20, 2026", swim: "1.3", bike: "", content: "游泳：400m暖身 + 12x50m節奏訓練 + 300m整理 | 跑步：40min輕鬆跑", hours: 2, type: "配速訓練", run: "7", week: "Week 2", phase: "基礎強化期" },
    { day: "Week 2 - Day 3 (週三)", status: "No", intensity: "高強度", date: "January 21, 2026", swim: "1", bike: "40", content: "自行車：12x20sec 120% FTP + 90sec輕鬆 | 跑步：40min輕鬆跑 | 游泳：30min輕鬆游", hours: 2.5, type: "間歇訓練", run: "7", week: "Week 2", phase: "基礎強化期" },
    { day: "Week 2 - Day 4 (週四)", status: "No", intensity: "高強度", date: "January 22, 2026", swim: "4.8", bike: "", content: "游泳：長距離耐力測試 4800m (6x50m暖身 + 主項 + 200m整理) | 瑜珈訓練", hours: 2, type: "耐力測試", run: "", week: "Week 2", phase: "基礎強化期" },
    { day: "Week 2 - Day 5 (週五)", status: "No", intensity: "高強度", date: "January 23, 2026", swim: "", bike: "", content: "跑步(早)：40min輕鬆跑 | 跑步(晚)：6x200m間歇", hours: 2, type: "間歇訓練", run: "10", week: "Week 2", phase: "基礎強化期" },
    { day: "Week 2 - Day 6 (週六)", status: "No", intensity: "中等", date: "January 24, 2026", swim: "", bike: "90", content: "自行車：3hrs有氧騎乘 | 下午休息", hours: 3, type: "長距離", run: "", week: "Week 2", phase: "基礎強化期" },
    { day: "Week 2 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "January 25, 2026", swim: "2", bike: "", content: "跑步：60min輕鬆跑 | 游泳：45min輕鬆游", hours: 2, type: "輕鬆恢復", run: "10", week: "Week 2", phase: "基礎強化期" },

    // Week 3 - 基礎強化期 (1/26-2/1)
    { day: "Week 3 - Day 1 (週一)", status: "No", intensity: "中等", date: "January 26, 2026", swim: "3.2", bike: "90", content: "自行車：90min輕鬆恢復 | 游泳：3200m (400m暖身 + 4x500m混合 + 200m整理)", hours: 3, type: "有氧訓練", run: "", week: "Week 3", phase: "基礎強化期" },
    { day: "Week 3 - Day 2 (週二)", status: "No", intensity: "中等", date: "January 27, 2026", swim: "2.6", bike: "", content: "游泳：350m暖身 + 2x500m姿勢調整 + 6x100m有氧 + 300m整理 | 跑步：60min慢跑", hours: 2.5, type: "配速訓練", run: "10", week: "Week 3", phase: "基礎強化期" },
    { day: "Week 3 - Day 3 (週三)", status: "No", intensity: "高強度", date: "January 28, 2026", swim: "", bike: "60", content: "自行車：60min FTP踏頻90+ | 跑步：男6x400m/女6x300m間歇", hours: 2, type: "間歇訓練", run: "8", week: "Week 3", phase: "基礎強化期" },
    { day: "Week 3 - Day 4 (週四)", status: "No", intensity: "中等", date: "January 29, 2026", swim: "2", bike: "", content: "跑步：2x1000m有氧 + 20min整理 | 瑜珈訓練", hours: 1.5, type: "有氧訓練", run: "6", week: "Week 3", phase: "基礎強化期" },
    { day: "Week 3 - Day 5 (週五)", status: "No", intensity: "高強度", date: "January 30, 2026", swim: "1.4", bike: "", content: "跑步(早)：70min輕鬆跑 | 跑步(晚)：12x100m踏頻 + 20min整理", hours: 2.5, type: "間歇訓練", run: "15", week: "Week 3", phase: "基礎強化期" },
    { day: "Week 3 - Day 6 (週六)", status: "No", intensity: "中等", date: "January 31, 2026", swim: "", bike: "75", content: "自行車：2.5hrs有氧騎乘 | 下午休息", hours: 2.5, type: "長距離", run: "", week: "Week 3", phase: "基礎強化期" },
    { day: "Week 3 - Day 7 (週日)", status: "No", intensity: "中等", date: "February 1, 2026", swim: "2", bike: "", content: "跑步：爬坡與平地間歇 7x30sec衝刺 | 游泳：45min輕鬆游約2km", hours: 2, type: "間歇訓練", run: "8", week: "Week 3", phase: "基礎強化期" },

    // Week 4 - 基礎強化期 (2/2-2/8)
    { day: "Week 4 - Day 1 (週一)", status: "No", intensity: "中等", date: "February 2, 2026", swim: "3.6", bike: "90", content: "自行車：90min輕鬆恢復 | 游泳：3600m (8x300m蛙/自 + 2x200m臂划 + 2x200m腿)", hours: 3, type: "有氧訓練", run: "", week: "Week 4", phase: "基礎強化期" },
    { day: "Week 4 - Day 2 (週二)", status: "No", intensity: "中等", date: "February 3, 2026", swim: "1.7", bike: "", content: "游泳：400m暖身 + 2x15min姿勢調整 + 250m整理 | 跑步：2x15min輕鬆跑", hours: 1.5, type: "技術課", run: "5", week: "Week 4", phase: "基礎強化期" },
    { day: "Week 4 - Day 3 (週三)", status: "No", intensity: "高強度", date: "February 4, 2026", swim: "", bike: "60", content: "自行車：45min輕鬆騎 + 105% FTP 4x5min | 跑步：45min輕鬆跑", hours: 2, type: "配速訓練", run: "8", week: "Week 4", phase: "基礎強化期" },
    { day: "Week 4 - Day 4 (週四)", status: "No", intensity: "中等", date: "February 5, 2026", swim: "3.6", bike: "", content: "游泳：3600m (6x50m自由式 + 2x300m臂划) | 瑜珈訓練", hours: 1.5, type: "技術課", run: "", week: "Week 4", phase: "基礎強化期" },
    { day: "Week 4 - Day 5 (週五)", status: "No", intensity: "中等", date: "February 6, 2026", swim: "", bike: "", content: "跑步(早)：70min輕鬆跑 | 核心訓練(心率Zone 2) + 呼吸練習", hours: 2, type: "有氧訓練", run: "12", week: "Week 4", phase: "基礎強化期" },
    { day: "Week 4 - Day 6 (週六)", status: "No", intensity: "中等", date: "February 7, 2026", swim: "", bike: "90", content: "自行車：3hrs有氧騎乘 心率Zone 2 55%-65% FTP | 下午休息", hours: 3, type: "長距離", run: "", week: "Week 4", phase: "基礎強化期" },
    { day: "Week 4 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "February 8, 2026", swim: "2", bike: "", content: "跑步：60min輕鬆跑 | 游泳：45min輕鬆游", hours: 2, type: "輕鬆恢復", run: "10", week: "Week 4", phase: "基礎強化期" },

    // Week 5 - 速度節奏強化期 (2/9-2/15)
    { day: "Week 5 - Day 1 (週一)", status: "No", intensity: "中等", date: "February 9, 2026", swim: "3.2", bike: "60", content: "自行車：踩踏/肌耐力訓練 50%-60% FTP | 游泳：3200m (8x50m呼吸 + 3x100m全力游)", hours: 2.5, type: "肌耐力訓練", run: "", week: "Week 5", phase: "速度節奏強化期" },
    { day: "Week 5 - Day 2 (週二)", status: "No", intensity: "高強度", date: "February 10, 2026", swim: "3", bike: "", content: "游泳：3km (2x800m輕鬆游) | 跑步：10x500m間歇", hours: 2.5, type: "間歇訓練", run: "10", week: "Week 5", phase: "速度節奏強化期" },
    { day: "Week 5 - Day 3 (週三)", status: "No", intensity: "高強度", date: "February 11, 2026", swim: "", bike: "105", content: "跑步(早)：30min慢跑 | 自行車：6x87% FTP 總長1hr45min (60% FTP)", hours: 3, type: "配速訓練", run: "5", week: "Week 5", phase: "速度節奏強化期" },
    { day: "Week 5 - Day 4 (週四)", status: "No", intensity: "中等", date: "February 12, 2026", swim: "2", bike: "", content: "游泳：水中/陸地訓練 4x500m混合游 | 瑜珈訓練", hours: 2, type: "技術課", run: "", week: "Week 5", phase: "速度節奏強化期" },
    { day: "Week 5 - Day 5 (週五)", status: "No", intensity: "高強度", date: "February 13, 2026", swim: "", bike: "", content: "跑步(早)：50min有氧跑 | 跑步(晚)：9x800m間歇", hours: 3, type: "間歇訓練", run: "18", week: "Week 5", phase: "速度節奏強化期" },
    { day: "Week 5 - Day 6 (週六)", status: "No", intensity: "中等", date: "February 14, 2026", swim: "", bike: "150", content: "🧧 除夕 | 自行車：5hrs輕鬆騎 | 下午休息", hours: 5, type: "長距離", run: "", week: "Week 5", phase: "速度節奏強化期", holiday: "除夕" },
    { day: "Week 5 - Day 7 (週日)", status: "No", intensity: "中等", date: "February 15, 2026", swim: "2", bike: "", content: "🧧 初一 | 跑步：2x400m爬坡訓練 | 游泳：45min輕鬆游", hours: 2, type: "間歇訓練", run: "6", week: "Week 5", phase: "速度節奏強化期", holiday: "初一" },

    // Week 6 - 速度節奏強化期 (2/16-2/22)
    { day: "Week 6 - Day 1 (週一)", status: "No", intensity: "中等", date: "February 16, 2026", swim: "3.9", bike: "", content: "🧧 初二 | 游泳：850m臂/腿 + 1500m輕鬆游 + 1500m姿勢調整", hours: 2, type: "技術課", run: "", week: "Week 6", phase: "速度節奏強化期", holiday: "初二" },
    { day: "Week 6 - Day 2 (週二)", status: "No", intensity: "高強度", date: "February 17, 2026", swim: "", bike: "90", content: "🧧 初三 | 跑步：3/3/2/1km間歇 | 自行車：3hrs輕鬆恢復", hours: 4, type: "間歇訓練", run: "12", week: "Week 6", phase: "速度節奏強化期", holiday: "初三" },
    { day: "Week 6 - Day 3 (週三)", status: "No", intensity: "中等", date: "February 18, 2026", swim: "", bike: "60", content: "🧧 初四 | 自行車：45min 3x5min 70% + 15min down 45% | 跑步：35min輕鬆跑", hours: 2, type: "配速訓練", run: "6", week: "Week 6", phase: "速度節奏強化期", holiday: "初四" },
    { day: "Week 6 - Day 4 (週四)", status: "No", intensity: "高強度", date: "February 19, 2026", swim: "3.5", bike: "", content: "🧧 初五 | 游泳：400m暖身 + 2x400m臂划 + 4x500m全力游 + 200m整理 | 瑜珈訓練", hours: 2, type: "配速訓練", run: "", week: "Week 6", phase: "速度節奏強化期", holiday: "初五" },
    { day: "Week 6 - Day 5 (週五)", status: "No", intensity: "高強度", date: "February 20, 2026", swim: "", bike: "", content: "跑步(早)：45min輕鬆跑 | 跑步(晚)：8x200m間歇", hours: 2, type: "間歇訓練", run: "12", week: "Week 6", phase: "速度節奏強化期" },
    { day: "Week 6 - Day 6 (週六)", status: "No", intensity: "中等", date: "February 21, 2026", swim: "", bike: "90", content: "自行車：3hrs有氧騎乘 70% FTP | 下午休息", hours: 3, type: "長距離", run: "", week: "Week 6", phase: "速度節奏強化期" },
    { day: "Week 6 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "February 22, 2026", swim: "2", bike: "", content: "跑步：60min有氧跑 | 游泳：45min輕鬆游約2km", hours: 2, type: "輕鬆恢復", run: "10", week: "Week 6", phase: "速度節奏強化期" },

    // Week 7 - 速度節奏強化期 (2/23-3/1)
    { day: "Week 7 - Day 1 (週一)", status: "No", intensity: "中等", date: "February 23, 2026", swim: "0.2", bike: "90", content: "自行車：90min輕鬆恢復 8x30m輕鬆 12x50sec/90sec快速 | 游泳：200m輕鬆游", hours: 2, type: "配速訓練", run: "", week: "Week 7", phase: "速度節奏強化期" },
    { day: "Week 7 - Day 2 (週二)", status: "No", intensity: "高強度", date: "February 24, 2026", swim: "1.7", bike: "", content: "游泳：250m暖身 + 12x50mx2(有氧/節奏/快速) + 250m整理 | 跑步：5x800m間歇", hours: 2, type: "間歇訓練", run: "10", week: "Week 7", phase: "速度節奏強化期" },
    { day: "Week 7 - Day 3 (週三)", status: "No", intensity: "中等", date: "February 25, 2026", swim: "", bike: "60", content: "自行車：60min 70%-85% FTP 3x5min 75%-85% | 跑步：30min輕鬆跑", hours: 2, type: "配速訓練", run: "5", week: "Week 7", phase: "速度節奏強化期" },
    { day: "Week 7 - Day 4 (週四)", status: "No", intensity: "高強度", date: "February 26, 2026", swim: "3.9", bike: "", content: "游泳：3900m (2x205m輕鬆游 + 4x100m混合) | 瑜珈訓練", hours: 2, type: "配速訓練", run: "", week: "Week 7", phase: "速度節奏強化期" },
    { day: "Week 7 - Day 5 (週五)", status: "No", intensity: "高強度", date: "February 27, 2026", swim: "", bike: "", content: "跑步(早)：8x200m間歇 | 跑步(晚)：60min輕鬆跑", hours: 2.5, type: "間歇訓練", run: "15", week: "Week 7", phase: "速度節奏強化期" },
    { day: "Week 7 - Day 6 (週六)", status: "No", intensity: "中等", date: "February 28, 2026", swim: "", bike: "120", content: "自行車：4hrs有氧騎乘 | 下午休息", hours: 4, type: "長距離", run: "", week: "Week 7", phase: "速度節奏強化期" },
    { day: "Week 7 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "March 1, 2026", swim: "2", bike: "", content: "跑步：60min輕鬆跑 | 游泳：45min輕鬆游約2km", hours: 2, type: "輕鬆恢復", run: "10", week: "Week 7", phase: "速度節奏強化期" },

    // Week 8 - 速度節奏強化期 (3/2-3/8)
    { day: "Week 8 - Day 1 (週一)", status: "No", intensity: "輕鬆", date: "March 2, 2026", swim: "3", bike: "60", content: "自行車：60min輕鬆恢復 | 游泳：3000m (8x50m姿勢調整)", hours: 2, type: "輕鬆恢復", run: "", week: "Week 8", phase: "速度節奏強化期" },
    { day: "Week 8 - Day 2 (週二)", status: "No", intensity: "中等", date: "March 3, 2026", swim: "1.2", bike: "", content: "游泳：2x200m輕鬆游 + 8x50m呼吸/換氣 + 200m整理 | 跑步：3x15min輕鬆跑", hours: 2, type: "技術課", run: "8", week: "Week 8", phase: "速度節奏強化期" },
    { day: "Week 8 - Day 3 (週三)", status: "No", intensity: "中等", date: "March 4, 2026", swim: "", bike: "75", content: "自行車：15min 50%暖身 + 4x4min 75%功課 + 45min整理 | 核心訓練(心率Zone 1-2)", hours: 2, type: "配速訓練", run: "", week: "Week 8", phase: "速度節奏強化期" },
    { day: "Week 8 - Day 4 (週四)", status: "No", intensity: "高強度", date: "March 5, 2026", swim: "3.7", bike: "", content: "游泳：3700m (6x50m衝刺 + 10x100m全力游) | 瑜珈訓練", hours: 2, type: "間歇訓練", run: "", week: "Week 8", phase: "速度節奏強化期" },
    { day: "Week 8 - Day 5 (週五)", status: "No", intensity: "中等", date: "March 6, 2026", swim: "", bike: "", content: "跑步(早)：60min有氧跑 | 跑步(晚)：2x20min輕鬆跑", hours: 2.5, type: "有氧訓練", run: "15", week: "Week 8", phase: "速度節奏強化期" },
    { day: "Week 8 - Day 6 (週六)", status: "No", intensity: "高強度", date: "March 7, 2026", swim: "", bike: "90", content: "自行車：3hrs騎乘 5min 70% FTP + 2min 85% FTP | 下午休息", hours: 3, type: "配速訓練", run: "", week: "Week 8", phase: "速度節奏強化期" },
    { day: "Week 8 - Day 7 (週日)", status: "No", intensity: "中等", date: "March 8, 2026", swim: "2", bike: "", content: "跑步：75min輕鬆跑 | 游泳：45min輕鬆游約2km", hours: 2.5, type: "輕鬆恢復", run: "12", week: "Week 8", phase: "速度節奏強化期" },

    // Week 9 - 速度節奏強化期 (3/9-3/15)
    { day: "Week 9 - Day 1 (週一)", status: "No", intensity: "中等", date: "March 9, 2026", swim: "2.5", bike: "90", content: "自行車：90min有氧騎乘 50%-60% FTP | 游泳：450m暖身 + 8x50m換氣/姿勢調整 + 8x50m出水面換氣 + 400m整理", hours: 3, type: "有氧訓練", run: "", week: "Week 9", phase: "速度節奏強化期" },
    { day: "Week 9 - Day 2 (週二)", status: "No", intensity: "高強度", date: "March 10, 2026", swim: "1.2", bike: "", content: "游泳：400m暖身 + 6x50m姿勢 + 2x50m腿 + 200m整理 | 跑步：2-3km暖身 + 3/2/1/1km間歇", hours: 2, type: "間歇訓練", run: "10", week: "Week 9", phase: "速度節奏強化期" },
    { day: "Week 9 - Day 3 (週三)", status: "No", intensity: "輕鬆", date: "March 11, 2026", swim: "", bike: "45", content: "自行車：45min輕鬆騎 50%-65% | 跑步：45min輕鬆跑", hours: 2, type: "輕鬆恢復", run: "8", week: "Week 9", phase: "速度節奏強化期" },
    { day: "Week 9 - Day 4 (週四)", status: "No", intensity: "高強度", date: "March 12, 2026", swim: "2.9", bike: "", content: "游泳：2900m (4x50m混合 + 4x50m全力游 + 200m整理) | 瑜珈訓練", hours: 1.5, type: "配速訓練", run: "", week: "Week 9", phase: "速度節奏強化期" },
    { day: "Week 9 - Day 5 (週五)", status: "No", intensity: "高強度", date: "March 13, 2026", swim: "", bike: "", content: "跑步(早)：50min慢跑(心率Zone 2) | 跑步(晚)：9x200m速度訓練", hours: 2, type: "間歇訓練", run: "12", week: "Week 9", phase: "速度節奏強化期" },
    { day: "Week 9 - Day 6 (週六)", status: "No", intensity: "中等", date: "March 14, 2026", swim: "", bike: "60", content: "自行車：60min身體檢測 + 3x12min輕鬆騎 | 下午休息", hours: 2, type: "輕鬆恢復", run: "", week: "Week 9", phase: "速度節奏強化期" },
    { day: "Week 9 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "March 15, 2026", swim: "2", bike: "", content: "游泳：45min輕鬆游約2km | 跑步：60min輕鬆跑(心率Zone 2)", hours: 2, type: "輕鬆恢復", run: "10", week: "Week 9", phase: "速度節奏強化期" },

    // Week 10 - 速度節奏強化期 (3/16-3/22)
    { day: "Week 10 - Day 1 (週一)", status: "No", intensity: "輕鬆", date: "March 16, 2026", swim: "1.5", bike: "75", content: "自行車：75min輕鬆恢復 | 游泳：12x50m速度訓練 + 250m整理游", hours: 2, type: "輕鬆恢復", run: "", week: "Week 10", phase: "速度節奏強化期" },
    { day: "Week 10 - Day 2 (週二)", status: "No", intensity: "高強度", date: "March 17, 2026", swim: "1.8", bike: "", content: "游泳：450m暖身 + 6x200m姿勢調整 + 150m整理 | 跑步：6x400m距離間歇", hours: 2, type: "間歇訓練", run: "8", week: "Week 10", phase: "速度節奏強化期" },
    { day: "Week 10 - Day 3 (週三)", status: "No", intensity: "高強度", date: "March 18, 2026", swim: "", bike: "120", content: "自行車：45min 50%功課 + 8x3min 115%踏頻 + 60min整理 | 跑步：35min輕鬆跑", hours: 3, type: "間歇訓練", run: "6", week: "Week 10", phase: "速度節奏強化期" },
    { day: "Week 10 - Day 4 (週四)", status: "No", intensity: "中等", date: "March 19, 2026", swim: "1.2", bike: "", content: "游泳：10x100m混合 + 200m整理游 | 瑜珈訓練", hours: 1, type: "配速訓練", run: "", week: "Week 10", phase: "速度節奏強化期" },
    { day: "Week 10 - Day 5 (週五)", status: "No", intensity: "高強度", date: "March 20, 2026", swim: "", bike: "", content: "跑步(早)：45min輕鬆跑 | 跑步(晚)：15x80m間歇", hours: 2, type: "間歇訓練", run: "10", week: "Week 10", phase: "速度節奏強化期" },
    { day: "Week 10 - Day 6 (週六)", status: "No", intensity: "中等", date: "March 21, 2026", swim: "", bike: "150", content: "自行車：5hrs輕鬆騎 | 下午休息", hours: 5, type: "長距離", run: "", week: "Week 10", phase: "速度節奏強化期" },
    { day: "Week 10 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "March 22, 2026", swim: "2", bike: "", content: "游泳：45min輕鬆游約2km | 跑步：45min輕鬆跑", hours: 1.5, type: "輕鬆恢復", run: "8", week: "Week 10", phase: "速度節奏強化期" },

    // Week 11 - 強化與調整期 (3/23-3/29)
    { day: "Week 11 - Day 1 (週一)", status: "No", intensity: "中等", date: "March 23, 2026", swim: "", bike: "90", content: "自行車：90min有氧騎乘 踏頻85-95rpm", hours: 1.5, type: "有氧訓練", run: "", week: "Week 11", phase: "強化調整期" },
    { day: "Week 11 - Day 2 (週二)", status: "No", intensity: "中等", date: "March 24, 2026", swim: "1.9", bike: "", content: "游泳：350m暖身 + 25x50m換氣/姿勢 + 250m整理 | 跑步：45min輕鬆跑 + 25min伸展", hours: 2, type: "技術課", run: "8", week: "Week 11", phase: "強化調整期" },
    { day: "Week 11 - Day 3 (週三)", status: "No", intensity: "中等", date: "March 25, 2026", swim: "", bike: "45", content: "自行車：45min有氧騎乘 75% + 4min rest", hours: 1, type: "配速訓練", run: "", week: "Week 11", phase: "強化調整期" },
    { day: "Week 11 - Day 4 (週四)", status: "No", intensity: "輕鬆", date: "March 26, 2026", swim: "0.8", bike: "", content: "游泳：500m姿勢調整 + 250m輕鬆游 | 瑜珈訓練", hours: 1, type: "技術課", run: "", week: "Week 11", phase: "強化調整期" },
    { day: "Week 11 - Day 5 (週五)", status: "No", intensity: "中等", date: "March 27, 2026", swim: "", bike: "", content: "跑步(早)：60min輕鬆跑 | 跑步(晚)：20-30min練習轉換(跑步)", hours: 2, type: "磚式訓練", run: "12", week: "Week 11", phase: "強化調整期" },
    { day: "Week 11 - Day 6 (週六)", status: "No", intensity: "中等", date: "March 28, 2026", swim: "", bike: "90", content: "自行車：3hrs有氧騎乘(每1.5hrs休息) | 下午休息", hours: 3, type: "長距離", run: "", week: "Week 11", phase: "強化調整期" },
    { day: "Week 11 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "March 29, 2026", swim: "2", bike: "", content: "跑步：60min輕鬆跑(心率Zone 2) | 游泳：45min輕鬆游約2km", hours: 2, type: "輕鬆恢復", run: "10", week: "Week 11", phase: "強化調整期" },

    // Week 12 - 強化與調整期 (3/30-4/5)
    { day: "Week 12 - Day 1 (週一)", status: "No", intensity: "輕鬆", date: "March 30, 2026", swim: "", bike: "60", content: "自行車：60min輕鬆恢復", hours: 1, type: "輕鬆恢復", run: "", week: "Week 12", phase: "強化調整期" },
    { day: "Week 12 - Day 2 (週二)", status: "No", intensity: "高強度", date: "March 31, 2026", swim: "1.2", bike: "", content: "游泳：300m暖身 + 12x50m換氣 + 250m整理 | 跑步：8x400m間歇", hours: 2, type: "間歇訓練", run: "8", week: "Week 12", phase: "強化調整期" },
    { day: "Week 12 - Day 3 (週三)", status: "No", intensity: "高強度", date: "April 1, 2026", swim: "", bike: "90", content: "自行車：90min輕鬆騎 50% 踏頻87-93rpm | 跑步：10x400m間歇", hours: 3, type: "間歇訓練", run: "10", week: "Week 12", phase: "強化調整期" },
    { day: "Week 12 - Day 4 (週四)", status: "No", intensity: "高強度", date: "April 2, 2026", swim: "1.8", bike: "", content: "游泳：10x100m蛙/自 + 6x50m全力游 + 200m整理 | 瑜珈訓練", hours: 1.5, type: "配速訓練", run: "", week: "Week 12", phase: "強化調整期" },
    { day: "Week 12 - Day 5 (週五)", status: "No", intensity: "中等", date: "April 3, 2026", swim: "", bike: "", content: "跑步(早)：5x100m衝刺 + 6km輕鬆跑 | 跑步(晚)：50min慢跑", hours: 2, type: "間歇訓練", run: "12", week: "Week 12", phase: "強化調整期" },
    { day: "Week 12 - Day 6 (週六)", status: "No", intensity: "高強度", date: "April 4, 2026", swim: "", bike: "120", content: "自行車：4hrs騎乘 10min 50% + 4x5min 90% FTP | 下午休息", hours: 4, type: "配速訓練", run: "", week: "Week 12", phase: "強化調整期" },
    { day: "Week 12 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "April 5, 2026", swim: "2", bike: "", content: "游泳：45min輕鬆游約2km | 跑步：45min輕鬆跑", hours: 1.5, type: "輕鬆恢復", run: "8", week: "Week 12", phase: "強化調整期" },

    // Week 13 - 強化與調整期 (4/6-4/12)
    { day: "Week 13 - Day 1 (週一)", status: "No", intensity: "輕鬆", date: "April 6, 2026", swim: "1.7", bike: "60", content: "自行車：60min輕鬆騎(功課50%) | 游泳：450m暖身 + 10x100m全力游 + 250m整理", hours: 2, type: "配速訓練", run: "", week: "Week 13", phase: "強化調整期" },
    { day: "Week 13 - Day 2 (週二)", status: "No", intensity: "中等", date: "April 7, 2026", swim: "0.6", bike: "", content: "游泳：200m暖身 + 8x50m呼吸練習 | 跑步：6x4km衝刺 + 15min伸展", hours: 2, type: "間歇訓練", run: "8", week: "Week 13", phase: "強化調整期" },
    { day: "Week 13 - Day 3 (週三)", status: "No", intensity: "中等", date: "April 8, 2026", swim: "", bike: "75", content: "自行車：75min暖身 78% + 2min輕鬆 | 跑步：45min輕鬆跑", hours: 2.5, type: "配速訓練", run: "8", week: "Week 13", phase: "強化調整期" },
    { day: "Week 13 - Day 4 (週四)", status: "No", intensity: "中等", date: "April 9, 2026", swim: "2.1", bike: "", content: "游泳：3x500m混合 + 4x100m姿勢調整 + 200m整理 | 瑜珈訓練", hours: 1.5, type: "配速訓練", run: "", week: "Week 13", phase: "強化調整期" },
    { day: "Week 13 - Day 5 (週五)", status: "No", intensity: "中等", date: "April 10, 2026", swim: "", bike: "", content: "跑步(早)：50min輕鬆跑 | 跑步(晚)：60min輕鬆跑", hours: 2, type: "有氧訓練", run: "15", week: "Week 13", phase: "強化調整期" },
    { day: "Week 13 - Day 6 (週六)", status: "No", intensity: "中等", date: "April 11, 2026", swim: "2", bike: "90", content: "自行車：3hrs有氧騎乘(保持姿勢、補水、補鹽) | 游泳：45min輕鬆游約2km", hours: 4, type: "長距離", run: "", week: "Week 13", phase: "強化調整期" },
    { day: "Week 13 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "April 12, 2026", swim: "", bike: "40", content: "自行車：40min輕鬆恢復 | 跑步：60min輕鬆跑", hours: 2, type: "輕鬆恢復", run: "10", week: "Week 13", phase: "強化調整期" },

    // Week 14 - 減量調整期 Tapering (4/13-4/19)
    { day: "Week 14 - Day 1 (週一)", status: "No", intensity: "輕鬆", date: "April 13, 2026", swim: "", bike: "60", content: "自行車：1hr輕鬆騎", hours: 1, type: "輕鬆恢復", run: "", week: "Week 14", phase: "減量期" },
    { day: "Week 14 - Day 2 (週二)", status: "No", intensity: "中等", date: "April 14, 2026", swim: "1.5", bike: "", content: "游泳：45min課表(1300-1600m) | 跑步：20min輕鬆跑 + 12x20sec/60sec衝刺", hours: 1.5, type: "配速訓練", run: "5", week: "Week 14", phase: "減量期" },
    { day: "Week 14 - Day 3 (週三)", status: "No", intensity: "輕鬆", date: "April 15, 2026", swim: "", bike: "45", content: "自行車：45min 50%功課", hours: 0.75, type: "輕鬆恢復", run: "", week: "Week 14", phase: "減量期" },
    { day: "Week 14 - Day 4 (週四)", status: "No", intensity: "輕鬆", date: "April 16, 2026", swim: "0.9", bike: "", content: "游泳：4x50m換氣/姿勢 + 600m輕鬆游 + 150m整理 | 瑜珈訓練", hours: 1, type: "技術課", run: "", week: "Week 14", phase: "減量期" },
    { day: "Week 14 - Day 5 (週五)", status: "No", intensity: "輕鬆", date: "April 17, 2026", swim: "", bike: "", content: "跑步(早)：30min暖身 + 5min伸展 | 跑步(晚)：20-30min練習轉換(跑步)", hours: 1, type: "磚式訓練", run: "6", week: "Week 14", phase: "減量期" },
    { day: "Week 14 - Day 6 (週六)", status: "No", intensity: "中等", date: "April 18, 2026", swim: "1", bike: "60", content: "自行車：60min輕鬆騎 + 30min全力游(比賽功率70-82%)", hours: 1.5, type: "配速訓練", run: "", week: "Week 14", phase: "減量期" },
    { day: "Week 14 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "April 19, 2026", swim: "2", bike: "", content: "游泳：45min輕鬆游約2km | 跑步：30min輕鬆跑(心率Zone 2)", hours: 1.5, type: "輕鬆恢復", run: "5", week: "Week 14", phase: "減量期" },

    // Week 15 - 賽前準備 (4/20-4/26)
    { day: "Week 15 - Day 1 (週一)", status: "No", intensity: "休息", date: "April 20, 2026", swim: "", bike: "", content: "完全休息日 - 調整身體狀態", hours: 0, type: "完全休息", run: "", week: "Week 15", phase: "賽前週" },
    { day: "Week 15 - Day 2 (週二)", status: "No", intensity: "輕鬆", date: "April 21, 2026", swim: "1", bike: "", content: "游泳：200m暖身 + 4x50m姿勢調整 + 4x100m中速 + 200m整理", hours: 0.75, type: "技術課", run: "", week: "Week 15", phase: "賽前週" },
    { day: "Week 15 - Day 3 (週三)", status: "No", intensity: "輕鬆", date: "April 22, 2026", swim: "", bike: "30", content: "自行車：15min 50%暖身 + 15min 23%(踏頻60rpm以上) + 10min 70%有氧 | 跑步：10min暖身 + 3x5min輕鬆跑", hours: 1, type: "賽前活化", run: "4", week: "Week 15", phase: "賽前週" },
    { day: "Week 15 - Day 4 (週四)", status: "No", intensity: "輕鬆", date: "April 23, 2026", swim: "0.5", bike: "", content: "跑步：20min輕鬆跑 | 游泳：10min輕鬆游 + 2x1min比賽節奏", hours: 0.75, type: "賽前活化", run: "3", week: "Week 15", phase: "賽前週" },
    { day: "Week 15 - Day 5 (週五)", status: "No", intensity: "輕鬆", date: "April 24, 2026", swim: "0.5", bike: "", content: "瑜珈訓練30min | 游泳：10min輕鬆游 + 2x1min比賽節奏", hours: 0.75, type: "賽前活化", run: "", week: "Week 15", phase: "賽前週" },
    { day: "Week 15 - Day 6 (週六) - 比賽日", status: "No", intensity: "最大", date: "April 25, 2026", swim: "1.9", bike: "90", content: "🏆 Challenge Taiwan 113 🏆 | 游泳 1.9km + 自行車 90km + 跑步 21.1km", hours: 5.5, type: "比賽日", run: "21.1", week: "Week 15", phase: "賽前週" },
    { day: "Week 15 - Day 7 (週日)", status: "No", intensity: "休息", date: "April 26, 2026", swim: "", bike: "", content: "完全休息日 - 恢復", hours: 0, type: "完全休息", run: "", week: "Week 15", phase: "賽前週" }
];

// Sort by date
garminTriData.sort((a, b) => new Date(a.date) - new Date(b.date));
